version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: airport-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airportdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: aviation-backend
    container_name: airport-backend
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/airportdb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
    ports:
      - '8081:8080'

volumes:
  mysql_data:
